### ISSUE TITLE
Error: please fill out both fields with unique info

### ISSUE THREAD

**Issue by janetmango** [Lamikins/HabitiFit#2]
Since the changeover to HabitiFit, my account was working correctly, but then lost my Habitica account info.  I re-input my API and User ID and got the error above. 

Thanks.

**Comment by Lamikins** [comment]
This is caused by a small error in item.js— it should be fixed now.  Let me
know if it still doesn't work.

**Comment by janetmango** [comment]
It works fine now.  Thanks.
