### ISSUE TITLE
Longer Authentication Span?

### ISSUE THREAD

**Issue by janetmango** [Lamikins/HabitiFit#3]
I've noticed that we have to re-authenticate our FitBit every day. Is there a way to make a longer span between authentications? Or is that used to designate a "day" right now (like Habitica's Cron?)

Thanks!

**Comment by Lamikins** [comment]
Authentication duration is an option on the FitBit authentication page.
When you press the authenticate button there should be a time span dropdown
option, where you can pick between various time lengths the longest of
which is 30 days.  Let me know if this works.

**Comment by janetmango** [comment]
Working fine. I revoked access on the FitBit side and re-authenticated to select 30 days.  Thanks again for your quick reply!!
