### ISSUE TITLE
Authenication Issue

### ISSUE THREAD

**Issue by magoo005** [Lamikins/HabitiFit#8]
When I try to authenticate with fitbit I get the error message "Your FitBit access code has expired. Please re-authenticate. Note: This is not a valid logout" The section for inputting my Habitica API and other settings flashes briefly and then disappears.  I'm logged into the fitbit website.  It worked fine the first two times I authenticated.
![habit](https://cloud.githubusercontent.com/assets/19763198/16837733/f0872b2a-4979-11e6-9c05-8ffdf4cf6bcf.png)

**Comment by casmith** [comment]
I'm having the same issue. I tried clearing site data for both fitbit.com and habitifit.herokuapp.com and the issue still persists.

**Comment by MaggieAppleton** [comment]
^ In the same boat. Any leads on fixing the issue?

**Comment by snales** [comment]
I'm experiencing this as well. Cleared the app connection from my Fitbit profile, no dice. Fix? Please?

**Comment by Lamikins** [comment]
Hello all, I have been busy for the past month but have a lot of free time coming up. Look forward to a fix in the next 2-3 days!

**Comment by snales** [comment]
Dude. You're the best. Looking forward to it for sure!

**Comment by Lamikins** [comment]
I migrated to Habitica's API v3 and updated some info on FitBit's side, so the site should work now. Please let me know if there are any other bugs.

**Comment by tiesselune** [comment]
It seems to work. Yay!

**Comment by snales** [comment]
Love it! Thank you so much for turning this around so quickly. Do you have somewhere we can go to contribute to you for this if we wish?

Because everyone likes a little extra for their work. 👍

**Comment by Lamikins** [comment]
@snales I'm working on it. Look out for a donate button on Habitifit soon :)

**Comment by Lamikins** [comment]
Habitifit works with new Habitica API.
